name: Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  security-scan:
    name: Run Safety Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install and upgrade pip
        run: |
          python -m pip install --upgrade pip==23.3.1

      # Install your python dependencies
      - name: Install python package or dependencies
        run: |
          pip install -e .

      - name: Upgrade setuptools
        run: pip install --upgrade setuptools

      - name: Install safety
        run: pip install safety

      - name: Run Safety Check
        run: |
          safety check
